security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'bcrypt'

    providers:
        app_user_provider:
            entity:
                class: Twitter\IAM\Domain\User\Model\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        login:
            pattern: ^/api/token$
            stateless: true
            json_login:
                check_path: /api/token
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure    
        refresh:
            pattern: ^/api/token/refresh$
            stateless: true
            refresh_jwt:
                check_path: /api/token/refresh
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/token, roles: PUBLIC_ACCESS }
        - { path: ^/api/health, roles: PUBLIC_ACCESS }
        - { path: ^/api/users, roles: PUBLIC_ACCESS }
        - { path: ^/api/registration, roles: PUBLIC_ACCESS }
        - { path: ^/api/profiles, methods: [GET], roles: PUBLIC_ACCESS }
        - { path: ^/api/tweets, methods: [GET], roles: PUBLIC_ACCESS }
        - { path: ^/api/tokens, roles: PUBLIC_ACCESS }
        - { path: ^/api/token/refresh$, roles: PUBLIC_ACCESS }
        - { path: ^/api/tweets/.+/likes/toggle, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
