# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

health_check_module:
    resource: ../src/HealthCheck/Controller/HealthCheckController.php
    type: attribute
    
iam_module:
    resource: ../src/IAM/UI/REST/Controller/
    type: attribute

registration_module:
    resource: ../src/Registration/UI/REST/Controller/
    type: attribute

iam_module_web:
    resource: ../src/IAM/UI/Web/*/*Controller.php
    type: attribute

like_module:
    resource: ../src/Like/UI/REST/Controller/
    type: attribute

profile_module:
    resource: ../src/Profile/UI/REST/Controller/*/*Controller.php
    type: attribute
    
profile_module_web:
    resource: ../src/Profile/UI/Web/*/*Controller.php
    type: attribute

tweet_module:
    resource: ../src/Tweet/UI/REST/*/*Controller.php
    type: attribute

api_login_check:
    path: /api/token
    methods: [POST]

web:
    resource: ../src/*/UI/Web/**/*Controller.php
    type: attribute
